'use client';
import {useCallback,useEffect,useState} from 'react';
import {CloudSun,RefreshCw,Wind} from 'lucide-react';
import {api} from '@/lib/client';
import {aqiLevel,isStale,weatherLabel} from '@/lib/environment';
import {type CityEnvironment,range} from '@/lib/city-environment';
const n=(v:number|null|undefined)=>v==null?'—':Math.round(v).toLocaleString('vi-VN');
const time=(value:number)=>new Date(value*1000).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'});
export default function EnvironmentPanel(){
 const[data,setData]=useState<CityEnvironment|null>(null);const[busy,setBusy]=useState(true);const[error,setError]=useState('');const[now,setNow]=useState(()=>Date.now());
 const load=useCallback(async(signal?:AbortSignal)=>{setBusy(true);setError('');try{const result=await api<CityEnvironment>('/api/environment/city',undefined,signal);if(!signal?.aborted){setData(result);setNow(Date.now())}}catch{if(!signal?.aborted)setError('Chưa cập nhật được dữ liệu.')}finally{if(!signal?.aborted)setBusy(false)}},[]);
 useEffect(()=>{const c=new AbortController();const initial=setTimeout(()=>void load(c.signal),0);const timer=setInterval(()=>{setNow(Date.now());if(document.visibilityState==='visible')void load(c.signal)},600000);return()=>{c.abort();clearTimeout(initial);clearInterval(timer)}},[load]);
 const temp=range(data?.points.map(p=>p.weather&&!isStale(p.weather.time,now)?p.weather.values.temperature_2m:null)??[]);
 const aqi=range(data?.points.map(p=>p.air&&!isStale(p.air.time,now)?p.air.values.us_aqi:null)??[]);
 const low=aqiLevel(aqi?.min);const high=aqiLevel(aqi?.max);
 const formatRange=(r:ReturnType<typeof range>)=>r?(Math.round(r.min)===Math.round(r.max)?n(r.min):`${n(r.min)}–${n(r.max)}`):'—';
 return <aside className="city-widget" aria-label="Thời tiết và không khí TP. Hồ Chí Minh"><div className="city-widget-top"><b>TP. Hồ Chí Minh</b><button className="icon-button" disabled={busy} onClick={()=>void load()} aria-label="Cập nhật thời tiết"><RefreshCw className={busy?'spin':''}/></button></div>
 <div className="city-readings" aria-live="polite"><span><CloudSun/><strong>{formatRange(temp)}°C</strong></span><span><Wind/><strong>{formatRange(aqi)}</strong> US AQI</span></div>
 <div className="city-aqi-status" aria-live="polite"><span className="city-aqi-label">Chất lượng không khí:</span>{aqi?<><span className={'aqi-'+low.tone}><span className="aqi-badge">{low.label}</span></span>{low.tone!==high.tone&&<><span className="aqi-between">đến</span><span className={'aqi-'+high.tone}><span className="aqi-badge">{high.label}</span></span></>}</>:<span className="aqi-badge">{busy?'Đang tải…':'Chưa có dữ liệu'}</span>}</div>
 <p className="city-aqi-hint">US AQI càng cao, mức ô nhiễm càng lớn.</p>
 <p className="city-caption">{busy&&!data?'Đang lấy thời tiết & không khí…':error||(!temp&&!aqi?'Chưa có dữ liệu hiện tại. Hãy thử cập nhật lại.':!temp?'Chưa có dữ liệu thời tiết hiện tại.':!aqi?'Chưa có dữ liệu không khí hiện tại.':'Khoảng giá trị tại 5 khu vực đại diện')}</p>
 <details className="city-details"><summary>Xem các khu vực & nguồn dữ liệu</summary><div className="city-details-body"><section className="city-aqi-legend" aria-label="Giải thích thang US AQI"><h3>Đọc chỉ số không khí</h3>{[{value:0,label:'0–50'},{value:51,label:'51–100'},{value:101,label:'101–150'},{value:151,label:'151–200'},{value:201,label:'201–300'},{value:301,label:'Trên 300'}].map(b=><div key={b.value} className={'aqi-'+aqiLevel(b.value).tone}><b>{b.label}</b><span className="aqi-badge">{aqiLevel(b.value).label}</span></div>)}<p>“Không tốt cho nhóm nhạy cảm” nghĩa là một số người nhạy cảm với ô nhiễm có thể bị ảnh hưởng sức khỏe. Đây là thang US AQI, không phải VN_AQI.</p><a href="https://www.airnow.gov/aqi/aqi-basics/" target="_blank" rel="noreferrer">Giải thích thang đo: AirNow / EPA</a></section><p>TP.HCM theo quy định mới nhất. Các điểm dưới đây giúp xem khác biệt giữa các khu vực; đây không phải trung bình hay phép đo bao phủ toàn thành phố.</p>
 {data?.points.map(p=><div className="city-point" key={p.id}><b>{p.name}</b><span>{n(p.weather?.values.temperature_2m)} °C · {p.weather?p.weather.source==='MET Norway'?'Ước tính theo giờ':weatherLabel(p.weather.values.weather_code):'Chưa có thời tiết'}</span><span className={'aqi-'+aqiLevel(p.air?.values.us_aqi).tone}>US AQI {n(p.air?.values.us_aqi)} · <span className="aqi-badge">{aqiLevel(p.air?.values.us_aqi).label}</span></span><small>Nguồn thời tiết: {p.weather?.source??'chưa có'} · Thời tiết: {p.weather?time(p.weather.time):'chưa có'} · Không khí: {p.air?time(p.air.time):'chưa có'} · giờ VN</small>{((p.weather&&isStale(p.weather.time,now))||(p.air&&isStale(p.air.time,now)))&&<small className="stale-message">Có dữ liệu cũ; đã loại khỏi khoảng giá trị phía trên.</small>}</div>)}
 {!busy&&(!temp||!aqi)&&<p>Một số dữ liệu đang thiếu hoặc quá cũ. Không thay thế bằng số liệu giả.</p>}{((temp&&temp.count<5)||(aqi&&aqi.count<5))&&<p>Khoảng giá trị hiện chỉ tính các điểm còn dữ liệu: thời tiết {temp?.count??0}/5, không khí {aqi?.count??0}/5.</p>}
 <p>Dữ liệu mô hình từ <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a> · nguồn thời tiết dự phòng <a href="https://www.met.no/" target="_blank" rel="noreferrer">MET Norway</a> · <a href="https://atmosphere.copernicus.eu/" target="_blank" rel="noreferrer">Copernicus CAMS</a> (<a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>). Không khí dùng lưới khoảng 45 km; US AQI không phải VN_AQI. Không lấy vị trí cá nhân. Tự cập nhật mỗi 10 phút khi trang đang mở.</p></div></details></aside>
}
