import type {Item, Rule, Source} from './domain';

type Definition = [string, string, Item['group'], string[], Item['questions'], boolean];

// These are searchable item types, not claims that a collection point accepts them.
export const additionalItemDefs: Definition[] = [
  ['nhiet-ke-thuy-ngan','Nhiệt kế thủy ngân','chemical',['nhiệt kế thuỷ ngân','cặp nhiệt độ thủy ngân','nhiệt kế thủy ngân bị vỡ','nhiệt kế thủy ngân vỡ','cặp nhiệt độ','mercury thermometer'],['intact'],true],
  ['nhiet-ke-dien-tu','Nhiệt kế điện tử','electronic',['nhiệt kế hồng ngoại','nhiệt kế đo trán','digital thermometer'],['intact'],true],
  ['thuoc-het-han','Thuốc hết hạn hoặc không dùng nữa','chemical',['thuốc tây','thuốc viên','thuốc thừa','thuốc kháng sinh','siro hết hạn'],[],true],
  ['vi-thuoc','Vỉ thuốc','other',['vỏ vỉ thuốc','vỉ thuốc nhôm nhựa'],['empty'],true],
  ['lo-thuoc','Chai, lọ đựng thuốc','other',['lọ thuốc','chai thuốc','lọ siro'],['empty','intact'],true],
  ['but-tiem-insulin','Bút tiêm insulin đã dùng','other',['bút tiêm','kim bút tiêm insulin'],[],true],
  ['kim-chich-mau','Kim chích máu đã dùng','other',['kim lấy máu','lancet','kim thử đường huyết'],[],true],
  ['thuoc-tru-sau','Thuốc bảo vệ thực vật còn dư','chemical',['thuốc trừ sâu','thuốc diệt cỏ','thuốc diệt chuột'],['intact'],true],
  ['binh-xit-con-trung','Bình xịt côn trùng','chemical',['bình xịt muỗi','chai xịt gián','bình aerosol'],['intact'],true],
  ['nuoc-tay','Nước tẩy mạnh còn dư','chemical',['javen','thuốc tẩy','nước tẩy bồn cầu'],['intact'],true],
  ['nuoc-thong-cong','Chất thông cống','chemical',['bột thông cống','nước thông cống','xút'],['intact'],true],
  ['dung-moi-son','Dung môi, chất pha sơn','chemical',['xăng thơm','dầu thông','thinner','dung môi tẩy rửa'],['intact'],true],
  ['son-mong-tay','Sơn và nước tẩy móng tay','chemical',['sơn móng','acetone','a xê tôn'],['intact'],true],
  ['dau-nhot','Dầu nhớt đã qua sử dụng','chemical',['nhớt thải','dầu máy','dầu bôi trơn'],['intact'],true],
  ['binh-gas-mini','Bình gas mini','chemical',['bình ga mini','bình gas du lịch','bình butane'],['intact'],true],
  ['bat-lua','Bật lửa','chemical',['hộp quẹt','quẹt gas','bật lửa còn gas'],['intact','empty'],true],
  ['pin-9v','Pin 9V','battery',['pin vuông','pin chín vôn'],['intact'],true],
  ['pin-xe-dien','Pin xe đạp, xe máy điện','battery',['pin xe điện','bộ pin xe','ắc quy xe điện'],['intact'],true],
  ['thuoc-la-dien-tu','Thuốc lá điện tử','chemical',['vape','pod','vape dùng một lần'],['intact'],true],
  ['may-tinh-bang','Máy tính bảng','electronic',['tablet','ipad'],['intact'],true],
  ['ban-phim','Bàn phím máy tính','electronic',['bàn phím','keyboard'],['intact'],true],
  ['chuot-may-tinh','Chuột máy tính','electronic',['chuột không dây','mouse'],['intact'],true],
  ['tai-nghe','Tai nghe','electronic',['tai nghe bluetooth','earbuds','airpods'],['intact'],true],
  ['loa','Loa và dàn âm thanh','electronic',['loa bluetooth','loa kéo','ampli'],['intact'],true],
  ['router','Bộ phát Wi-Fi','electronic',['router','modem','cục wifi'],['intact'],true],
  ['day-cap','Dây cáp điện, cáp sạc','electronic',['dây sạc','dây điện','cáp USB','cáp mạng'],['intact'],true],
  ['cu-sac','Củ sạc, bộ đổi nguồn','electronic',['adapter','cục sạc','củ sạc điện thoại'],['intact'],true],
  ['quat-dien','Quạt điện','electronic',['quạt bàn','quạt đứng','quạt máy'],['intact'],true],
  ['noi-com-dien','Nồi cơm điện','electronic',['nồi điện'],['intact'],true],
  ['ban-ui','Bàn ủi','electronic',['bàn là'],['intact'],true],
  ['may-say-toc','Máy sấy tóc','electronic',['máy sấy'],['intact'],true],
  ['may-giat','Máy giặt','electronic',['máy giặt cũ'],['intact'],true],
  ['dieu-hoa','Máy điều hòa','electronic',['máy lạnh','cục nóng điều hòa'],['intact'],true],
  ['lo-vi-song','Lò vi sóng','electronic',['microwave'],['intact'],true],
  ['chai-dau-goi','Chai dầu gội','plastic',['vỏ chai dầu gội'],['clean','empty'],false],
  ['chai-sua-tam','Chai sữa tắm','plastic',['chai nước rửa tay','chai mỹ phẩm không chứa chất nguy hại'],['clean','empty'],false],
  ['nap-chai-nhua','Nắp chai nhựa','plastic',['nắp nhựa'],['clean'],false],
  ['can-nhua-thuc-pham','Can nhựa đựng thực phẩm','plastic',['can nước','can dầu ăn rỗng'],['clean','empty'],false],
  ['sach','Sách cũ','paper',['sách giáo khoa','truyện','sách báo'],['clean'],false],
  ['tap-vo','Tập, vở học sinh','paper',['vở cũ','tập cũ','sổ tay'],['clean'],false],
  ['tap-chi','Tạp chí','paper',['tạp chí cũ','catalogue giấy'],['clean'],false],
  ['tui-giay','Túi giấy','paper',['bao giấy','túi kraft'],['clean'],false],
  ['loi-giay','Lõi cuộn giấy','paper',['lõi giấy vệ sinh','ống giấy'],['clean'],false],
  ['giay-goi-qua','Giấy gói quà tráng phủ','other',['giấy gói kim tuyến','giấy bóng gói quà','giấy gói ánh kim'],[],false],
  ['mang-boc-thuc-pham','Màng bọc thực phẩm','plastic',['màng PE','màng bọc nhựa'],['clean'],false],
  ['tui-zip','Túi nhựa có khóa kéo','plastic',['túi zip','túi ziplock'],['clean'],false],
  ['xop-bong-bong','Màng xốp bong bóng','plastic',['xốp hơi','túi bóng khí','bubble wrap'],['clean'],false],
  ['ly-giay','Ly giấy có lớp phủ','other',['cốc giấy','ly cà phê giấy','ly giấy tráng nhựa'],['empty'],false],
  ['muong-nhua','Muỗng, nĩa nhựa dùng một lần','other',['thìa nhựa','dĩa nhựa','dao nhựa'],[],false],
  ['nhua-phan-huy','Bao bì nhựa ghi compostable','other',['nhựa sinh học','túi phân hủy sinh học','túi compostable','PLA'],[],false],
  ['rau-hong','Rau củ hỏng','organic',['rau úa','rau bỏ đi'],[],false],
  ['trai-cay-hong','Trái cây hỏng','organic',['hoa quả hỏng','trái cây úng'],[],false],
  ['ba-tra','Bã trà rời','organic',['bã chè','lá trà đã pha'],[],false],
  ['co-cat','Cỏ sau khi cắt','organic',['cỏ khô','cỏ vườn'],[],false],
  ['canh-cay','Cành cây lớn','bulky',['cành cây','gốc cây'],[],false],
  ['noi-chao','Nồi, chảo kim loại','metal',['xoong nồi','chảo nhôm','nồi inox'],['clean'],false],
  ['nap-chai-kim-loai','Nắp chai kim loại','metal',['nắp chai bia','nắp sắt'],['clean'],false],
  ['ta-bim','Tã, bỉm sinh hoạt đã dùng','other',['bỉm em bé','tã giấy','tã người lớn'],[],false],
  ['bang-ve-sinh','Băng vệ sinh đã dùng','other',['tampon','băng vệ sinh'],[],false],
  ['khan-uot','Khăn ướt đã dùng','other',['giấy ướt','khăn giấy ướt'],[],false],
  ['khau-trang','Khẩu trang sinh hoạt thông thường','other',['khẩu trang đã dùng','khẩu trang y tế'],[],false],
  ['ban-chai','Bàn chải đánh răng','other',['bàn chải nhựa'],[],false],
  ['vo-kem-danh-rang','Vỏ tuýp kem đánh răng','other',['tuýp kem đánh răng','vỏ kem đánh răng'],['empty'],false],
  ['chan','Chăn, mền cũ','other',['mền cũ','chăn cũ'],['clean'],false],
  ['tu-go','Tủ gỗ cũ','bulky',['tủ quần áo','tủ hỏng'],[],false],
  ['vali','Vali cũ','other',['va li','va ly'],['clean'],false],
  ['lop-xe','Lốp, săm xe','other',['vỏ xe','ruột xe','lốp xe máy','săm xe đạp'],[],false],
  ['xe-dap','Xe đạp cũ không gắn pin','bulky',['xe đạp','khung xe đạp'],[],false],
  ['den-pin','Đèn pin','electronic',['đèn pin sạc'],['intact'],true],
  ['dao-keo','Dao, kéo kim loại','metal',['dao nhà bếp','kéo cũ'],[],false],
  ['luoi-dao-cao','Lưỡi dao cạo','other',['dao lam','lưỡi lam'],[],false],
  ['ly-thuy-tinh','Ly, cốc thủy tinh','other',['cốc thủy tinh','ly uống nước thủy tinh'],['intact'],false],
];

export const materialDetails: Record<string, string> = {
  'nhiet-ke-thuy-ngan': 'Thủy tinh và thủy ngân · cần thu gom riêng',
  'nhiet-ke-dien-tu': 'Thiết bị điện tử có pin',
  'thuoc-het-han': 'Dược phẩm · cần hướng dẫn theo loại thuốc',
  'vi-thuoc': 'Bao bì nhôm / nhựa, có thể còn thuốc',
  'lo-thuoc': 'Bao bì dược phẩm, cần kiểm tra phần còn lại',
  'kim-tiem': 'Vật sắc nhọn y tế',
  'but-tiem-insulin': 'Dụng cụ tiêm, có thể còn kim và thuốc',
  'kim-chich-mau': 'Vật sắc nhọn y tế',
  'bat-lua': 'Vật dụng có thể còn gas dễ cháy',
  'thuoc-la-dien-tu': 'Thiết bị có pin và dung dịch nicotine',
};

export const additionalSources: Source[] = [
  {id:'epa-mercury-spill',name:'US EPA · Nhiệt kế thủy ngân bị vỡ',url:'https://www.epa.gov/mercury/what-do-if-mercury-thermometer-breaks',checkedAt:'2026-10-06',scope:'Hướng dẫn an toàn khi có thủy ngân; không phải danh sách nơi tiếp nhận tại Việt Nam.'},
  {id:'epa-mercury-storage',name:'US EPA · Lưu giữ và bàn giao vật chứa thủy ngân',url:'https://www.epa.gov/mercury/storing-transporting-and-disposing-mercury',checkedAt:'2026-10-06',scope:'Nguyên tắc bảo quản; phải hỏi đơn vị địa phương trước khi vận chuyển.'},
  {id:'epa-lamp-spill',name:'US EPA · Bóng huỳnh quang bị vỡ',url:'https://www.epa.gov/mercury/cleaning-broken-cfl',checkedAt:'2026-10-06',scope:'Giảm phơi nhiễm khi bóng chứa thủy ngân bị vỡ; không áp dụng quy định rác sinh hoạt của Hoa Kỳ cho Việt Nam.'},
  {id:'fda-medicine',name:'FDA · Thuốc hết hạn và không dùng nữa',url:'https://www.fda.gov/consumers/consumer-updates/where-and-how-dispose-unused-medicines',checkedAt:'2026-10-06',scope:'Ưu tiên hỏi chương trình thu hồi thuốc; không mặc định nhà thuốc Việt Nam nhận lại và không áp dụng danh sách xả thuốc của Hoa Kỳ.'},
  {id:'fda-sharps',name:'FDA · Thu gom kim tiêm và vật sắc nhọn',url:'https://www.fda.gov/medical-devices/safely-using-sharps-needles-and-syringes-home-work-and-travel/dos-and-donts-proper-sharps-disposal',checkedAt:'2026-10-06',scope:'Nguyên tắc bảo vệ người thu gom; hỏi cơ sở y tế về phương án bàn giao tại địa phương.'},
  {id:'epa-vape',name:'US EPA · Thu hồi thuốc lá điện tử',url:'https://www.epa.gov/hw/how-safely-dispose-e-cigarettes-information-individuals',checkedAt:'2026-10-06',scope:'Nguyên tắc xử lý pin và nicotine; không xác nhận điểm tiếp nhận trong nước.'},
  {id:'vn-sorting',name:'Bộ TN&MT · Hướng dẫn phân loại 9368/BTNMT-KSONMT',url:'https://mongcai.gov.vn/vi-vn/tin/bo-tnmt-ban-hanh-huong-dan-k%E1%BB%B9-thuat-ve-phan-loai-chat-thai-ran-sinh-hoat-p412241-c640884-n246249',checkedAt:'2026-10-06',scope:'Hướng dẫn kỹ thuật được cổng thông tin chính quyền đăng tải; cách thu gom cụ thể theo địa phương và đơn vị tiếp nhận.'},
];

function specific(id:string, itemIds:string[], category:Rule['category'], where:string, steps:string[], sourceIds:string[], options:Partial<Pick<Rule,'conditions'|'special'|'avoid'|'hazard'|'priority'>>={}):Rule {
  return {id,name:where,group:'',itemIds,areaId:'all',conditions:{},category,where,steps,sourceIds,priority:100,version:1,status:'published',validFrom:'2026-10-06',validTo:null,special:false,avoid:'',...options};
}

const medicineSteps = ['Giữ nhãn tên thuốc, để xa trẻ em; không dùng hoặc cho người khác thuốc hết hạn.','Hỏi dược sĩ hoặc cơ sở y tế về chương trình thu hồi phù hợp; liên hệ trước khi mang đến.'];
const mercurySpillSteps = [
  'Cho người và vật nuôi rời khu vực, tránh giẫm lên chỗ đổ tràn; không để trẻ em dọn.',
  'Mở cửa thông ra ngoài, đóng cửa sang phòng khác để hạn chế lan truyền.',
  'Liên hệ cơ quan y tế, môi trường hoặc đơn vị xử lý chuyên trách trước khi thu dọn, vận chuyển. Nếu thấy không khỏe sau phơi nhiễm, tìm trợ giúp y tế ngay.',
];

export const additionalRules: Rule[] = [
  specific('mercury-intact',['nhiet-ke-thuy-ngan'],'special','Đơn vị có xác nhận nhận chất thải chứa thủy ngân',[
    'Giữ nguyên nhiệt kế, đặt trong hộp chắc có nắp và chống va đập; ghi rõ có thủy ngân.',
    'Để xa trẻ em, vật nuôi; hỏi nơi tiếp nhận về cách đóng gói trước khi mang đi.',
  ],['epa-mercury-storage','vn-sorting'],{special:true,conditions:{intact:true},avoid:'Không bỏ vào rác sinh hoạt, thùng chai lọ thủy tinh hoặc thùng thu gom pin khi chưa có xác nhận nhận thủy ngân.'}),
  specific('mercury-spill',['nhiet-ke-thuy-ngan'],'special','Ưu tiên tránh tiếp xúc và hạn chế thủy ngân phát tán',mercurySpillSteps,['epa-mercury-spill'],{special:true,hazard:true,conditions:{intact:false},avoid:'Không dùng máy hút bụi, chổi; không đổ xuống cống hoặc đi lại bằng giày có thể dính thủy ngân.'}),
  specific('fluorescent-intact',['bong-den'],'special','Điểm có xác nhận nhận bóng đèn chứa thủy ngân',['Giữ nguyên bóng và chống va đập.','Hỏi riêng điều kiện nhận bóng đèn; không suy từ việc nơi đó nhận pin hoặc chai lọ.'],['vn-sorting'],{special:true,conditions:{intact:true},avoid:'Không đập vỡ bóng để giảm thể tích.'}),
  specific('fluorescent-broken',['bong-den'],'special','Cho người và vật nuôi rời khu vực bóng đèn vỡ',[
    'Mở cửa ra ngoài và rời phòng 5–10 phút; tắt hệ thống điều hòa thông gió trung tâm nếu có.',
    'Tránh giẫm lên mảnh vỡ. Xem hướng dẫn nguồn hoặc hỏi đơn vị chuyên trách về thu dọn và chứa kín mảnh đèn.',
    'Xác nhận nơi nhận chất thải chứa thủy ngân trước khi bàn giao.',
  ],['epa-lamp-spill'],{special:true,hazard:true,conditions:{intact:false},avoid:'Không dùng máy hút bụi để thu dọn ban đầu; không trộn mảnh bóng vào chai lọ tái chế.'}),
  specific('medicine-unused',['thuoc-het-han'],'special','Hỏi chương trình thu hồi thuốc hoặc dược sĩ',medicineSteps,['fda-medicine'],{special:true,avoid:'Không tự đổ thuốc xuống bồn cầu/cống hoặc trộn vào bao bì tái chế. Cách xử lý phụ thuộc loại thuốc.'}),
  specific('medicine-pack-not-empty',['vi-thuoc','lo-thuoc'],'special','Xử lý phần thuốc còn lại trước khi phân loại bao bì',medicineSteps,['fda-medicine'],{special:true,conditions:{empty:false},avoid:'Không rửa thuốc còn lại xuống cống hoặc bỏ lẫn với chai lọ sạch.'}),
  specific('blister-empty',['vi-thuoc'],'residual','Rác còn lại theo hướng dẫn thu gom tại nơi ở',['Chỉ áp dụng khi đã hết thuốc; nếu nơi thu gom có chương trình riêng cho vỉ thuốc, hỏi điều kiện trước.'],['vn-sorting'],{special:true,conditions:{empty:true},avoid:'Vỉ nhôm–nhựa không mặc định thuộc thùng nhựa hoặc kim loại tái chế.'}),
  specific('medicine-bottle-empty',['lo-thuoc'],'unknown','Xác nhận vật liệu và yêu cầu với bao bì đựng thuốc',['Giữ nhãn để nơi tiếp nhận biết loại thuốc từng chứa.','Chỉ giao vào luồng tái chế khi đơn vị đó xác nhận chấp nhận bao bì này.'],['vn-sorting','fda-medicine'],{special:true,conditions:{empty:true,intact:true},avoid:'Bao bì thuốc độc tế bào hoặc thuốc có yêu cầu riêng cần hỏi cơ sở y tế.'}),
  specific('medical-sharps',['kim-tiem','but-tiem-insulin','kim-chich-mau'],'special','Hỏi cơ sở y tế về nơi bàn giao vật sắc nhọn đã dùng',[
    'Cho kim và vật sắc nhọn vào hộp chuyên dụng chống đâm xuyên ngay sau khi dùng; để xa trẻ em.',
    'Đóng hộp theo hướng dẫn của cơ sở y tế; hỏi nơi tiếp nhận trước khi bàn giao.',
  ],['fda-sharps'],{special:true,avoid:'Không bỏ kim rời vào túi rác hoặc thùng tái chế; không bẻ, tháo hay chụp lại nắp kim bằng tay.'}),
  specific('pressurized-container',['binh-gas-mini','binh-xit-con-trung','bat-lua'],'special','Liên hệ nơi bán hoặc đơn vị nhận bình áp lực, hóa chất',[
    'Giữ nhãn và để xa nguồn nhiệt; hỏi rõ đơn vị có nhận đúng loại bình hay không.',
    'Không tự xả phần còn lại để làm rỗng. Nếu rò rỉ, tránh tiếp cận và hỏi đơn vị chuyên trách.',
  ],['epa-hazard','vn-sorting'],{special:true,avoid:'Không chọc thủng, ép dẹp, đốt hoặc tự nạp lại bình.'}),
  specific('lighter-empty',['bat-lua'],'residual','Rác còn lại theo hướng dẫn địa phương',['Chỉ áp dụng khi chắc chắn đã hết gas và vật còn nguyên vẹn.'],['vn-sorting'],{special:true,priority:120,conditions:{empty:true,intact:true},avoid:'Không tự xả, đốt hoặc chọc thủng để kiểm tra bình đã hết gas.'}),
  specific('vape-device',['thuoc-la-dien-tu'],'special','Đơn vị có tiếp nhận cả pin và chất thải nicotine',['Giữ nguyên thiết bị; liên hệ xác nhận loại sản phẩm và dung dịch còn lại.'],['epa-vape'],{special:true,avoid:'Không bỏ vào rác thường hoặc thùng tái chế; không tự tháo pin hay đổ dung dịch nicotine ra ngoài.'}),
  specific('vehicle-battery',['pin-xe-dien'],'special','Liên hệ hãng xe hoặc đơn vị chuyên thu hồi pin xe',['Giữ nguyên bộ pin; cung cấp loại xe và tình trạng pin cho nơi tiếp nhận.'],['epa-battery','epa-recycle'],{special:true,avoid:'Không tự tháo bộ pin; thùng pin gia dụng không mặc định nhận pin xe.'}),
  specific('accumulator',['ac-quy'],'special','Nơi bán hoặc đơn vị chuyên thu hồi đúng loại ắc quy',['Kiểm tra loại ắc quy trên nhãn, giữ nguyên và hỏi cách bàn giao.'],['epa-battery'],{special:true,avoid:'Không đổ dung dịch bên trong hoặc bỏ vào rác sinh hoạt.'}),
  specific('special-electronics',['den-led','tu-lanh','dieu-hoa','may-giat','lo-vi-song'],'special','Hỏi chương trình thu hồi đúng loại thiết bị',['Giữ nguyên thiết bị; đặt lịch bàn giao với đơn vị có tiếp nhận.'],['vn-sorting'],{special:true,avoid:'Không tự tháo các bộ phận bên trong.'}),
  specific('plastic-film',['tui-nilon','mang-boc-thuc-pham','tui-zip','xop-bong-bong'],'unknown','Hỏi điểm chuyên nhận túi và màng nhựa',['Tách riêng, xác nhận yêu cầu về độ sạch và loại màng.'],['epa-recycle'],{avoid:'Không mặc định bỏ cùng chai nhựa; nhiều hệ thống không nhận màng nhựa.'}),
  specific('compostable-plastic',['nhua-phan-huy'],'unknown','Kiểm tra nhãn và chương trình nhận loại bao bì này',['Hỏi hệ thống ủ phù hợp có chấp nhận sản phẩm cụ thể hay không.'],['epa-recycle'],{avoid:'Không trộn với nhựa tái chế; nhãn compostable không đồng nghĩa ủ được tại nhà.'}),
  specific('composite-packaging',['ly-giay','hop-sua','giay-goi-qua','bao-bi'],'unknown','Hỏi chương trình nhận đúng loại bao bì nhiều lớp',['Xác nhận vật liệu và điều kiện tiếp nhận trước khi bỏ vào nhóm giấy hoặc nhựa.'],['epa-recycle'],{avoid:'Lớp phủ, nhôm hoặc kim tuyến có thể làm thay đổi cách thu gom.'}),
  specific('everyday-residual',['ta-bim','bang-ve-sinh','khan-uot','khau-trang','giay-an','ban-chai','vo-kem-danh-rang','muong-nhua','ong-hut','hop-xop'],'residual','Thùng rác còn lại theo nhãn và hướng dẫn tại nơi ở',['Gói gọn để không rơi vãi; chỉ áp dụng cho rác sinh hoạt thông thường.'],['vn-sorting'],{avoid:'Đồ nghi lây nhiễm, dính máu hoặc hóa chất: hỏi cơ sở y tế/đơn vị chuyên trách, không áp dụng hướng dẫn rác thông thường.'}),
  specific('textile-reuse',['quan-ao','giay-dep','chan','vali'],'unknown','Ưu tiên tái sử dụng; hỏi chương trình thu gom đồ cũ',['Đồ còn tốt có thể sửa hoặc trao tặng; đồ hỏng cần xác nhận nơi nhận.'],['epa-recycle'],{avoid:'Không gửi đồ dính hóa chất hoặc mất vệ sinh cho chương trình quyên góp.'}),
  specific('large-household',['nem','ghe','tu-go','xe-dap','canh-cay'],'unknown','Hẹn đơn vị thu gom đồ cồng kềnh tại khu vực',['Hỏi lịch, cách bàn giao và phí nếu có; không đặt chắn lối đi.'],['vn-sorting']),
  specific('tires',['lop-xe'],'unknown','Hỏi cơ sở sửa xe hoặc chương trình thu hồi lốp',['Liên hệ trước để xác nhận có nhận loại lốp, săm này không.'],['epa-recycle'],{avoid:'Không đốt hoặc vứt lốp xuống ao, kênh, đất trống.'}),
  specific('household-sharps',['guong','gom','ly-thuy-tinh','luoi-dao-cao','dao-keo'],'unknown','Xác nhận cách giao vật sắc nhọn với đơn vị thu gom',['Che chắn cạnh sắc, chứa chắc và ghi cảnh báo để người thu gom nhận biết.'],['vn-sorting'],{avoid:'Không bỏ mảnh vỡ hoặc lưỡi dao rời vào bao rác; không áp dụng cách này cho kim tiêm đã dùng.'}),
  specific('cooked-food',['com','xuong'],'organic','Luồng thu gom thực phẩm phù hợp tại nơi ở',['Tách bao bì, đựng kín để hạn chế rò rỉ và mùi.'],['vn-sorting','epa-organic'],{avoid:'Không mặc định thịt, xương, dầu mỡ phù hợp với thùng ủ tại nhà.'}),
  specific('garden-and-tea',['ba-tra','co-cat','la'],'organic','Chương trình thu gom hoặc ủ hữu cơ chấp nhận vật liệu này',['Tách túi trà và bao bì; kiểm tra vật liệu trước khi ủ.'],['epa-organic'],{avoid:'Không dùng cỏ đã xử lý thuốc diệt cỏ hoặc cây bệnh cho đống ủ tại nhà.'}),
];
