import {z} from 'zod';
import {db,config} from './repository';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export function json(value:unknown,status=200){return Response.json(value,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
export async function handle(fn:()=>Promise<Response>){try{return await fn()}catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);if(e instanceof z.ZodError)return json({error:'Thông tin chưa hợp lệ. Hãy kiểm tra các trường đã nhập.',details:e.issues.map(x=>({path:x.path.join('.'),message:x.message}))},400);console.error('request_failed',e instanceof Error?e.name:'Unknown');return json({error:'Chưa kết nối được dữ liệu. Vui lòng thử lại.'},503)}}
export async function body(req:Request,limit=32000){if(Number(req.headers.get('content-length')??0)>limit)throw new HttpError(413,'Dữ liệu quá lớn.');const reader=req.body?.getReader();if(!reader)throw new HttpError(400,'Thiếu dữ liệu.');let total=0;const chunks:Uint8Array[]=[];while(true){const{value,done}=await reader.read();if(done)break;total+=value.length;if(total>limit){await reader.cancel();throw new HttpError(413,'Dữ liệu quá lớn.')}chunks.push(value)}const b=new Uint8Array(total);let offset=0;for(const c of chunks){b.set(c,offset);offset+=c.length}try{return JSON.parse(new TextDecoder().decode(b))}catch{throw new HttpError(400,'Dữ liệu không hợp lệ.')}}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new HttpError(403,'Nguồn yêu cầu không hợp lệ.');if(!req.headers.get('content-type')?.includes('application/json'))throw new HttpError(415,'Chỉ nhận JSON.');}
export async function admin(){const u=await getChatGPTUser();if(!u)throw new HttpError(401,'Hãy đăng nhập để quản trị.');const allowed=config('ADMIN_EMAILS').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(!allowed.includes(u.email.toLowerCase()))throw new HttpError(403,'Tài khoản chưa được cấp quyền quản trị.');return u}
export async function rate(req:Request,action:string,max=20){const day=Math.floor(Date.now()/3600000);const raw=`${req.headers.get('cf-connecting-ip')??'unknown'}:${action}:${day}`;const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)))).map(x=>x.toString(16).padStart(2,'0')).join('');const result=await db().prepare('INSERT INTO rate_limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(hash,Date.now()+3600000).first<{count:number}>();if(!result||result.count>max)throw new HttpError(429,'Bạn đã gửi nhiều yêu cầu. Vui lòng thử lại sau.');await db().prepare('DELETE FROM rate_limits WHERE expires < ?').bind(Date.now()).run()}
// One counter for the whole site per UTC day (Workers AI's free allocation resets at 00:00 UTC). Keeps image recognition
// inside the free allowance, and bounds the bill if the account ever moves to a paid plan.
export async function dailyCap(action:string,max:number){const day=new Date().toISOString().slice(0,10);const result=await db().prepare('INSERT INTO rate_limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(`cap:${action}:${day}`,Date.parse(day)+86400000).first<{count:number}>();if(!result||result.count>max)throw new HttpError(429,'Hôm nay đã hết lượt nhận diện ảnh miễn phí. Bạn vẫn có thể tra cứu bằng tên; lượt mới mở lúc 7 giờ sáng.')}
