// Only PNG generated by browser canvas is accepted by the server adapter.
export function sanitizePng(bytes:Uint8Array){if(bytes.length>6*1024*1024||bytes.length<33)throw new Error('Ảnh không hợp lệ hoặc quá lớn.');if([137,80,78,71,13,10,26,10].some((b,i)=>bytes[i]!==b))throw new Error('Định dạng ảnh không hợp lệ.');const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);const out:Uint8Array[]=[bytes.slice(0,8)];let offset=8,seenHeader=false,seenData=false,seenEnd=false;while(offset+12<=bytes.length){const len=view.getUint32(offset);if(len>bytes.length-offset-12)throw new Error('Ảnh bị hỏng.');const type=String.fromCharCode(...bytes.slice(offset+4,offset+8));if(!seenHeader&&type!=='IHDR')throw new Error('Thiếu thông tin ảnh.');if(type==='IHDR'){if(seenHeader||len!==13)throw new Error('Ảnh không hợp lệ.');const w=view.getUint32(offset+8),h=view.getUint32(offset+12);if(!w||!h||w*h>4000000)throw new Error('Ảnh vượt giới hạn 4 triệu pixel.');if(bytes[offset+16]!==8||![2,6].includes(bytes[offset+17])||bytes[offset+18]||bytes[offset+19]||bytes[offset+20])throw new Error('Hãy chọn lại ảnh để chuẩn hóa.');seenHeader=true}if(type==='IDAT')seenData=true;if(['IHDR','IDAT','IEND'].includes(type))out.push(bytes.slice(offset,offset+len+12));if(type==='IEND'){if(len!==0)throw new Error('Ảnh không hợp lệ.');seenEnd=true;break}offset+=len+12}if(!seenHeader||!seenData||!seenEnd)throw new Error('Ảnh bị thiếu dữ liệu.');const result=new Uint8Array(out.reduce((n,x)=>n+x.length,0));let n=0;for(const part of out){result.set(part,n);n+=part.length}return result}
export function validateImageFile(file: Pick<File, 'type' | 'size' | 'name'>) {
 const supported = ['image/jpeg', 'image/png', 'image/webp'];
 const extension = /\.(jpe?g|png|webp)$/i.test(file.name);
 if ((!supported.includes(file.type) && !(file.type === '' && extension))) throw new Error('Định dạng chưa hỗ trợ. Hãy chọn JPEG, PNG hoặc WebP; với HEIC, hãy xuất ảnh sang JPEG.');
 if (!file.size) throw new Error('Tệp ảnh đang trống. Hãy chọn lại ảnh.');
 if (file.size > 15*1024*1024) throw new Error('Ảnh vượt quá 15 MB. Hãy chọn ảnh nhỏ hơn.');
}
async function decodeImage(file: File): Promise<{source: CanvasImageSource; width: number; height: number; close: () => void}> {
 if (typeof createImageBitmap === 'function') {
  try { const bitmap = await createImageBitmap(file); return {source:bitmap,width:bitmap.width,height:bitmap.height,close:()=>bitmap.close()}; } catch { /* Try the browser image decoder below. */ }
 }
 const url = URL.createObjectURL(file);
 try {
  const img = new Image();
  await new Promise<void>((resolve,reject)=>{
   const timer=setTimeout(()=>reject(new Error('Xử lý ảnh quá lâu. Hãy chọn ảnh nhỏ hơn.')),15000);
   img.onload=()=>{clearTimeout(timer);resolve()};
   img.onerror=()=>{clearTimeout(timer);reject(new Error('Không đọc được ảnh này. Hãy chụp lại hoặc chọn một ảnh JPEG, PNG, WebP khác.'))};
   img.src=url;
  });
  return {source:img,width:img.naturalWidth,height:img.naturalHeight,close:()=>URL.revokeObjectURL(url)};
 } catch(e) { URL.revokeObjectURL(url); throw e; }
}
export async function prepareImage(file: File) {
 validateImageFile(file);
 const decoded = await decodeImage(file);
 try {
  if (!decoded.width || !decoded.height || decoded.width*decoded.height>48000000) throw new Error('Ảnh vượt giới hạn 48 triệu pixel hoặc bị lỗi. Hãy giảm độ phân giải rồi thử lại.');
  const ratio=Math.min(1,1400/Math.max(decoded.width,decoded.height));
  const canvas=document.createElement('canvas');
  canvas.width=Math.max(1,Math.round(decoded.width*ratio));canvas.height=Math.max(1,Math.round(decoded.height*ratio));
  const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Thiết bị chưa hỗ trợ xử lý ảnh.');
  ctx.drawImage(decoded.source,0,0,canvas.width,canvas.height);
  const data=canvas.toDataURL('image/png');
  if(!data.startsWith('data:image/png;base64,') || data.length>8*1024*1024)throw new Error('Ảnh quá lớn sau xử lý. Hãy chọn ảnh nhỏ hơn.');
  return data.split(',')[1];
 } finally { decoded.close(); }
}
