import {z} from 'zod';import {catalog,db,kinds,type Kind} from '@/lib/repository';import {handle,json,body,sameOrigin,admin,HttpError} from '@/lib/http';import {itemSchema,ruleSchema,pointSchema,sourceSchema,areaSchema,rulesOverlap,classify,idSchema} from '@/lib/domain';
const schemas={items:itemSchema,rules:ruleSchema,points:pointSchema,sources:sourceSchema,areas:areaSchema};
export const GET=()=>handle(async()=>{const user=await admin();const [c,drafts,feedback,audit,versions]=await Promise.all([catalog(),db().prepare('SELECT * FROM drafts').all(),db().prepare('SELECT * FROM feedback ORDER BY created_at DESC LIMIT 100').all(),db().prepare('SELECT * FROM audit_log ORDER BY created_at DESC LIMIT 100').all(),db().prepare('SELECT kind,id,version FROM records').all()]);return json({catalog:c,drafts:drafts.results,feedback:feedback.results,audit:audit.results,versions:versions.results,user:user.displayName})});
export const POST=(req:Request)=>handle(async()=>{sameOrigin(req);const user=await admin();const b=z.object({action:z.enum(['draft','publish','preview','resolve','restore']),kind:z.enum(['items','rules','points','sources','areas']).optional(),payload:z.unknown().optional(),id:idSchema.optional(),version:z.number().int().min(0).default(0),itemId:idSchema.optional(),areaId:idSchema.optional(),answers:z.object({clean:z.boolean().optional(),empty:z.boolean().optional(),intact:z.boolean().optional()}).optional()}).parse(await body(req,64000));const now=new Date().toISOString();
 if(b.action==='resolve'){if(!b.id)throw new HttpError(400,'Thiếu mã phản hồi.');await db().batch([db().prepare('UPDATE feedback SET status=? WHERE id=?').bind('reviewed',b.id),db().prepare('INSERT INTO audit_log (id,actor,kind,target,action,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),user.userId,'feedback',b.id,'reviewed',now)]);return json({ok:true})}
 const kind=b.kind as Kind;if(!kinds.includes(kind))throw new HttpError(400,'Thiếu loại dữ liệu.');let payload=b.payload;
 if(b.action==='restore'){const old=await db().prepare('SELECT before FROM audit_log WHERE id=? AND kind=?').bind(b.id,kind).first<{before:string|null}>();if(!old?.before)throw new HttpError(400,'Không có phiên bản trước để khôi phục.');payload=JSON.parse(old.before)}
 const value=schemas[kind].parse(payload);const c=await catalog();
 if(kind==='rules'){const r=ruleSchema.parse(value);if(!c.sources.some(s=>r.sourceIds.includes(s.id))||r.sourceIds.some(id=>!c.sources.some(s=>s.id===id)))throw new HttpError(400,'Quy tắc cần nguồn tồn tại.');if(r.itemIds.some(id=>!c.items.some(i=>i.id===id)))throw new HttpError(400,'Vật dụng chưa tồn tại.');if(!c.areas.some(a=>a.id===r.areaId))throw new HttpError(400,'Khu vực chưa tồn tại.');if(b.action==='preview'){const test={...c,rules:[...c.rules.filter(x=>x.id!==r.id),{...r,status:'published' as const}]};return json({result:classify(test,b.itemId??r.itemIds[0]??'',b.areaId??'all',b.answers??{}),conflicts:c.rules.filter(x=>rulesOverlap({...r,status:'published'},x)).map(x=>x.name)})}if(b.action==='publish'&&r.status==='published'&&c.rules.some(x=>rulesOverlap(r,x)))throw new HttpError(409,'Quy tắc chồng lấn. Hãy sửa phạm vi, điều kiện hoặc mức ưu tiên.')}
 if(kind==='points'){const p=pointSchema.parse(value);if(!c.areas.some(a=>a.id===p.areaId&&a.cityId==='hcm')||!c.sources.some(s=>s.id===p.scopeSourceId))throw new HttpError(400,'Cần khu vực TP.HCM và nguồn xác minh phạm vi.');for(const a of p.acceptance)if(!c.sources.some(s=>s.id===a.sourceId)||a.itemIds.some(id=>!c.items.some(i=>i.id===id)))throw new HttpError(400,'Kiểm tra nguồn và vật dụng tiếp nhận.');if(p.latitude!==null&&!p.coordinateSource)throw new HttpError(400,'Tọa độ cần nguồn xác định.');}
 if(kind==='areas'&&!c.sources.some(s=>s.id===areaSchema.parse(value).sourceId))throw new HttpError(400,'Khu vực cần nguồn tồn tại.');
 const current=await db().prepare('SELECT payload,version FROM records WHERE kind=? AND id=?').bind(kind,value.id).first<{payload:string;version:number}>();const currentVersion=current?.version??0;if(currentVersion!==b.version)throw new HttpError(409,'Dữ liệu đã thay đổi. Hãy tải lại trước khi lưu.');
 const payloadText=JSON.stringify(value);
 if(b.action==='draft'||b.action==='restore'){await db().prepare('INSERT INTO drafts(kind,id,payload,base_version,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(kind,id) DO UPDATE SET payload=excluded.payload,base_version=excluded.base_version,updated_at=excluded.updated_at').bind(kind,value.id,payloadText,currentVersion,now).run();return json({ok:true,draft:true})}
 const before=current?.payload??JSON.stringify((c[kind] as {id:string}[]).find(x=>x.id===value.id)??null);
 // Optimistic update must succeed before audit/delete. Batch is atomic; unique revision token is checked below.
 const write=current?db().prepare('UPDATE records SET payload=?,version=version+1,updated_at=? WHERE kind=? AND id=? AND version=?').bind(payloadText,now,kind,value.id,currentVersion):db().prepare('INSERT OR IGNORE INTO records(kind,id,payload,version,updated_at) VALUES (?,?,?,1,?)').bind(kind,value.id,payloadText,now);
 const auditId=crypto.randomUUID();const batch=await db().batch([write,db().prepare('INSERT INTO audit_log(id,actor,kind,target,action,before,after,created_at) SELECT ?,?,?,?,?,?,?,? WHERE changes()=1').bind(auditId,user.userId,kind,value.id,'publish',before,payloadText,now),db().prepare('DELETE FROM drafts WHERE kind=? AND id=? AND base_version=? AND EXISTS (SELECT 1 FROM audit_log WHERE id=?)').bind(kind,value.id,currentVersion,auditId)]);if(!batch[0].meta.changes)throw new HttpError(409,'Dữ liệu vừa được cập nhật. Hãy tải lại.');return json({ok:true});
});
